using System;
using System.Collections;


namespace Business.Data
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class Err_IO
	{

		#region Private Members

		private string m_pointname; 
		private string m_kkscode; 
		private string m_direction; 
		private string m_datatype; 
		private string m_description; 		
		#endregion

		#region Constuctor

		public Err_IO()
		{
			m_pointname = String.Empty; 
			m_kkscode = String.Empty; 
			m_direction = String.Empty; 
			m_datatype = String.Empty; 
			m_description = String.Empty; 
		}

		#region Public Properties
			
		public string PointName
		{
			get { return m_pointname; }

			set	
			{	
				if(  value != null &&  value.Length > 255)
					throw new ArgumentOutOfRangeException("Invalid value for PointName", value, value.ToString());
				
				m_pointname = value;
			}
		}
			
		public string KksCode
		{
			get { return m_kkscode; }

			set	
			{	
				if(  value != null &&  value.Length > 255)
					throw new ArgumentOutOfRangeException("Invalid value for KksCode", value, value.ToString());
				
				m_kkscode = value;
			}
		}
			
		public string Direction
		{
			get { return m_direction; }

			set	
			{	
				if(  value != null &&  value.Length > 255)
					throw new ArgumentOutOfRangeException("Invalid value for Direction", value, value.ToString());
				
				m_direction = value;
			}
		}
			
		public string DataType
		{
			get { return m_datatype; }

			set	
			{	
				if(  value != null &&  value.Length > 255)
					throw new ArgumentOutOfRangeException("Invalid value for DataType", value, value.ToString());
				
				m_datatype = value;
			}
		}
			
		public string Description
		{
			get { return m_description; }

			set	
			{	
				if(  value != null &&  value.Length > 0)
					throw new ArgumentOutOfRangeException("Invalid value for Description", value, value.ToString());
				
				m_description = value;
			}
		}
			
				
		#endregion 

		#region Private Accessors for NHibernate
		
		
		private string m_PointName
		{
			get { return m_pointname; }
			set { m_pointname = value; }
		}

		
		private string m_KKSCode
		{
			get { return m_kkscode; }
			set { m_kkscode = value; }
		}

		
		private string m_Direction
		{
			get { return m_direction; }
			set { m_direction = value; }
		}

		
		private string m_DataType
		{
			get { return m_datatype; }
			set { m_datatype = value; }
		}

		
		private string m_Description
		{
			get { return m_description; }
			set { m_description = value; }
		}

		#endregion // Internal Accessors for NHibernate 

		#region Public Functions

		#endregion //Public Functions

		#region Equals And HashCode Overrides
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			Err_IO castObj = (Err_IO)obj; 
			return castObj.GetHashCode() == this.GetHashCode();
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			return this.GetType().FullName.GetHashCode();
				
		}
		#endregion
			}
}
