using System;
using System.Collections;


namespace Business.Data
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class IOMap
	{

		#region Private Members

		private string m_kkscode; 
		private string m_iomapname; 		
		#endregion

		#region Constuctor

		public IOMap()
		{
			m_kkscode = String.Empty; 
			m_iomapname = String.Empty; 
		}

		#region Public Properties
			
		public string KksCode
		{
			get { return m_kkscode; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for KksCode", value, value.ToString());
				
				m_kkscode = value;
			}
		}
			
		public string IoMapName
		{
			get { return m_iomapname; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for IoMapName", value, value.ToString());
				
				m_iomapname = value;
			}
		}
			
				
		#endregion 

		#region Private Accessors for NHibernate
		
		
		private string m_KKSCode
		{
			get { return m_kkscode; }
			set { m_kkscode = value; }
		}

		
		private string m_IOMapName
		{
			get { return m_iomapname; }
			set { m_iomapname = value; }
		}

		#endregion // Internal Accessors for NHibernate 

		#region Public Functions

		#endregion //Public Functions

		#region Equals And HashCode Overrides
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			IOMap castObj = (IOMap)obj; 
			return castObj.GetHashCode() == this.GetHashCode();
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			return this.GetType().FullName.GetHashCode();
				
		}
		#endregion
			}
}
