using System;
using System.Collections;


namespace Business.Data
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class Prj_Sheet
	{

		#region Private Members

		private string m_controlleraddress; 
		private string m_documentname; 
		private string m_sheetname; 
		private int m_sheetnum; 
		private string m_order; 		
		#endregion

		#region Constuctor

		public Prj_Sheet()
		{
			m_controlleraddress = String.Empty; 
			m_documentname = String.Empty; 
			m_sheetname = String.Empty; 
			m_sheetnum = 0; 
			m_order = String.Empty; 
		}

		#region Public Properties
			
		public string ControllerAddress
		{
			get { return m_controlleraddress; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for ControllerAddress", value, value.ToString());
				
				m_controlleraddress = value;
			}
		}
			
		public string DocumentName
		{
			get { return m_documentname; }

			set	
			{	
				if(  value != null &&  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for DocumentName", value, value.ToString());
				
				m_documentname = value;
			}
		}
			
		public string SheetName
		{
			get { return m_sheetname; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for SheetName", value, value.ToString());
				
				m_sheetname = value;
			}
		}
			
		public int SheetNum
		{
			get { return m_sheetnum; }
			set
			{
				m_sheetnum = value;
			}

		}
			
		public string Order
		{
			get { return m_order; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Order", value, value.ToString());
				
				m_order = value;
			}
		}
			
				
		#endregion 

		#region Private Accessors for NHibernate
		
		
		private string m_ControllerAddress
		{
			get { return m_controlleraddress; }
			set { m_controlleraddress = value; }
		}

		
		private string m_DocumentName
		{
			get { return m_documentname; }
			set { m_documentname = value; }
		}

		
		private string m_SheetName
		{
			get { return m_sheetname; }
			set { m_sheetname = value; }
		}

		
		private int m_SheetNum
		{
			get { return m_sheetnum; }
			set { m_sheetnum = value; }
		}

		
		private string m_Order
		{
			get { return m_order; }
			set { m_order = value; }
		}

		#endregion // Internal Accessors for NHibernate 

		#region Public Functions

		#endregion //Public Functions

		#region Equals And HashCode Overrides
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			Prj_Sheet castObj = (Prj_Sheet)obj; 
			return castObj.GetHashCode() == this.GetHashCode();
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			return this.GetType().FullName.GetHashCode();
				
		}
		#endregion
			}
}
