using System;
using System.Collections;


namespace Business.Data
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class Prj_Project
	{

		#region Private Members

		private string m_projectname; 
		private DateTime m_createtime; 
		private DateTime m_modifytime; 
		private string m_type; 
		private string m_blockmaxnumber; 
		private string m_pinmaxnumber; 
		private string m_projectpath; 
		private string m_varsystemversion; 
		private string m_alarmversion; 		
		#endregion

		#region Constuctor

		public Prj_Project()
		{
			m_projectname = String.Empty; 
			m_createtime = DateTime.MinValue; 
			m_modifytime = DateTime.MinValue; 
			m_type = String.Empty; 
			m_blockmaxnumber = String.Empty; 
			m_pinmaxnumber = String.Empty; 
			m_projectpath = String.Empty; 
			m_varsystemversion = String.Empty; 
			m_alarmversion = String.Empty; 
		}

		public Prj_Project(
			string projectname)
			: this()
		{
			m_projectname = projectname;
			m_createtime = DateTime.MinValue;
			m_modifytime = DateTime.MinValue;
			m_type = String.Empty;
			m_blockmaxnumber = String.Empty;
			m_pinmaxnumber = String.Empty;
			m_projectpath = String.Empty;
			m_varsystemversion = String.Empty;
			m_alarmversion = String.Empty;
		}
		#endregion // End Constructor

		#region Public Properties
			
		public string ProjectName
		{
			get { return m_projectname; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for ProjectName", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for ProjectName", value, value.ToString());
				
				m_projectname = value;
			}
		}
			
		public DateTime CreateTime
		{
			get { return m_createtime; }
			set
			{
				m_createtime = value;
			}

		}
			
		public DateTime ModifyTime
		{
			get { return m_modifytime; }
			set
			{
				m_modifytime = value;
			}

		}
			
		public string Type
		{
			get { return m_type; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Type", value, value.ToString());
				
				m_type = value;
			}
		}
			
		public string BlockMaxNumber
		{
			get { return m_blockmaxnumber; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for BlockMaxNumber", value, value.ToString());
				
				m_blockmaxnumber = value;
			}
		}
			
		public string PinMaxNumber
		{
			get { return m_pinmaxnumber; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for PinMaxNumber", value, value.ToString());
				
				m_pinmaxnumber = value;
			}
		}
			
		public string ProjectPath
		{
			get { return m_projectpath; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for ProjectPath", value, value.ToString());
				
				m_projectpath = value;
			}
		}
			
		public string VarSystemVersion
		{
			get { return m_varsystemversion; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for VarSystemVersion", value, value.ToString());
				
				m_varsystemversion = value;
			}
		}
			
		public string AlarmVersion
		{
			get { return m_alarmversion; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for AlarmVersion", value, value.ToString());
				
				m_alarmversion = value;
			}
		}
			
				
		#endregion 

		#region Private Accessors for NHibernate
		
		
		private string m_ProjectName
		{
			get { return m_projectname; }
			set { m_projectname = value; }
		}

		
		private DateTime m_CreateTime
		{
			get { return m_createtime; }
			set { m_createtime = value; }
		}

		
		private DateTime m_ModifyTime
		{
			get { return m_modifytime; }
			set { m_modifytime = value; }
		}

		
		private string m_Type
		{
			get { return m_type; }
			set { m_type = value; }
		}

		
		private string m_BlockMaxNumber
		{
			get { return m_blockmaxnumber; }
			set { m_blockmaxnumber = value; }
		}

		
		private string m_PinMaxNumber
		{
			get { return m_pinmaxnumber; }
			set { m_pinmaxnumber = value; }
		}

		
		private string m_ProjectPath
		{
			get { return m_projectpath; }
			set { m_projectpath = value; }
		}

		
		private string m_VarSystemVersion
		{
			get { return m_varsystemversion; }
			set { m_varsystemversion = value; }
		}

		
		private string m_AlarmVersion
		{
			get { return m_alarmversion; }
			set { m_alarmversion = value; }
		}

		#endregion // Internal Accessors for NHibernate 

		#region Public Functions

		#endregion //Public Functions

		#region Equals And HashCode Overrides
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			Prj_Project castObj = (Prj_Project)obj; 
			return ( castObj != null ) &&
				( this.m_projectname == castObj.ProjectName );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			
			int hash = 57; 
			hash = 27 * hash * m_projectname.GetHashCode();
			return hash; 
		}
		#endregion
			}
}
