using System;
using System.Collections;


namespace Business.Data
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class Temp_FC
	{

		#region Private Members

		private string m_objectid; 
		private string m_fcbelong; 
		private string m_pinrelations; 
		private bool m_ref; 		
		#endregion

		#region Constuctor

		public Temp_FC()
		{
			m_objectid = String.Empty; 
			m_fcbelong = String.Empty; 
			m_pinrelations = String.Empty; 
			m_ref = false; 
		}

		public Temp_FC(
			bool ref)
			: this()
		{
			m_objectid = String.Empty;
			m_fcbelong = String.Empty;
			m_pinrelations = String.Empty;
			m_ref = ref;
		}
		#endregion // End Constructor

		#region Public Properties
			
		public string Objectid
		{
			get { return m_objectid; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Objectid", value, value.ToString());
				
				m_objectid = value;
			}
		}
			
		public string FcBelong
		{
			get { return m_fcbelong; }

			set	
			{	
				if(  value != null &&  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for FcBelong", value, value.ToString());
				
				m_fcbelong = value;
			}
		}
			
		public string PinRelations
		{
			get { return m_pinrelations; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for PinRelations", value, value.ToString());
				
				m_pinrelations = value;
			}
		}
			
		public bool Ref
		{
			get { return m_ref; }
			set
			{
				m_ref = value;
			}

		}
			
				
		#endregion 

		#region Private Accessors for NHibernate
		
		
		private string m_ObjectID
		{
			get { return m_objectid; }
			set { m_objectid = value; }
		}

		
		private string m_FcBelong
		{
			get { return m_fcbelong; }
			set { m_fcbelong = value; }
		}

		
		private string m_PinRelations
		{
			get { return m_pinrelations; }
			set { m_pinrelations = value; }
		}

		
		private bool m_Ref
		{
			get { return m_ref; }
			set { m_ref = value; }
		}

		#endregion // Internal Accessors for NHibernate 

		#region Public Functions

		#endregion //Public Functions

		#region Equals And HashCode Overrides
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			Temp_FC castObj = (Temp_FC)obj; 
			return castObj.GetHashCode() == this.GetHashCode();
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			return this.GetType().FullName.GetHashCode();
				
		}
		#endregion
			}
}
