using System;
using System.Collections;


namespace Business.Data
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class Temp_FCDetail
	{

		#region Private Members

		private string m_objectid; 
		private string m_pinname; 
		private string m_pinvalue; 
		private bool m_ishistory; 
		private string m_fcbelong; 
		private string m_signalbelone; 
		private string m_point; 
		private string m_detailtype; 
		private string m_controlleraddress; 
		private string m_documentname; 		
		#endregion

		#region Constuctor

		public Temp_FCDetail()
		{
			m_objectid = String.Empty; 
			m_pinname = String.Empty; 
			m_pinvalue = String.Empty; 
			m_ishistory = false; 
			m_fcbelong = String.Empty; 
			m_signalbelone = String.Empty; 
			m_point = String.Empty; 
			m_detailtype = String.Empty; 
			m_controlleraddress = String.Empty; 
			m_documentname = String.Empty; 
		}

		public Temp_FCDetail(
			bool ishistory)
			: this()
		{
			m_objectid = String.Empty;
			m_pinname = String.Empty;
			m_pinvalue = String.Empty;
			m_ishistory = ishistory;
			m_fcbelong = String.Empty;
			m_signalbelone = String.Empty;
			m_point = String.Empty;
			m_detailtype = String.Empty;
			m_controlleraddress = String.Empty;
			m_documentname = String.Empty;
		}
		#endregion // End Constructor

		#region Public Properties
			
		public string Objectid
		{
			get { return m_objectid; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Objectid", value, value.ToString());
				
				m_objectid = value;
			}
		}
			
		public string PinName
		{
			get { return m_pinname; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for PinName", value, value.ToString());
				
				m_pinname = value;
			}
		}
			
		public string PinValue
		{
			get { return m_pinvalue; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for PinValue", value, value.ToString());
				
				m_pinvalue = value;
			}
		}
			
		public bool IsHistory
		{
			get { return m_ishistory; }
			set
			{
				m_ishistory = value;
			}

		}
			
		public string FcBelong
		{
			get { return m_fcbelong; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for FcBelong", value, value.ToString());
				
				m_fcbelong = value;
			}
		}
			
		public string SignalBelone
		{
			get { return m_signalbelone; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for SignalBelone", value, value.ToString());
				
				m_signalbelone = value;
			}
		}
			
		public string Point
		{
			get { return m_point; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Point", value, value.ToString());
				
				m_point = value;
			}
		}
			
		public string DetailType
		{
			get { return m_detailtype; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for DetailType", value, value.ToString());
				
				m_detailtype = value;
			}
		}
			
		public string ControllerAddress
		{
			get { return m_controlleraddress; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for ControllerAddress", value, value.ToString());
				
				m_controlleraddress = value;
			}
		}
			
		public string DocumentName
		{
			get { return m_documentname; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for DocumentName", value, value.ToString());
				
				m_documentname = value;
			}
		}
			
				
		#endregion 

		#region Private Accessors for NHibernate
		
		
		private string m_ObjectID
		{
			get { return m_objectid; }
			set { m_objectid = value; }
		}

		
		private string m_PinName
		{
			get { return m_pinname; }
			set { m_pinname = value; }
		}

		
		private string m_PinValue
		{
			get { return m_pinvalue; }
			set { m_pinvalue = value; }
		}

		
		private bool m_IsHistory
		{
			get { return m_ishistory; }
			set { m_ishistory = value; }
		}

		
		private string m_FcBelong
		{
			get { return m_fcbelong; }
			set { m_fcbelong = value; }
		}

		
		private string m_SignalBelone
		{
			get { return m_signalbelone; }
			set { m_signalbelone = value; }
		}

		
		private string m_Point
		{
			get { return m_point; }
			set { m_point = value; }
		}

		
		private string m_DetailType
		{
			get { return m_detailtype; }
			set { m_detailtype = value; }
		}

		
		private string m_ControllerAddress
		{
			get { return m_controlleraddress; }
			set { m_controlleraddress = value; }
		}

		
		private string m_DocumentName
		{
			get { return m_documentname; }
			set { m_documentname = value; }
		}

		#endregion // Internal Accessors for NHibernate 

		#region Public Functions

		#endregion //Public Functions

		#region Equals And HashCode Overrides
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			Temp_FCDetail castObj = (Temp_FCDetail)obj; 
			return castObj.GetHashCode() == this.GetHashCode();
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			return this.GetType().FullName.GetHashCode();
				
		}
		#endregion
			}
}
